### ISSUE TITLE
Move to official org?

### ISSUE THREAD

**Issue by zenorocha** [dracula/ida#1]
Hey @oppsec 👋 

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by 0xdsm** [comment]
Hello @zenorocha !

Thanks for that awesome idea, of course I accept transferring my repository to the Dracula repository, just explain me how to do that and I'll do most fast possible

Best regards,
oppsec.

**Comment by zenorocha** [comment]
Great! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by 0xdsm** [comment]
Hey @zenorocha I already accepted the invite and you invited me with owner permissions, is that right?

**Comment by zenorocha** [comment]
Yes, you'll need that in order to transfer it. You can now go to your repo Settings and look for the Transfer section.

**Comment by 0xdsm** [comment]
Done, I already transfered the repository, thanks again @zenorocha 

Best regards,
oppsec.

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/ida

**Comment by 0xdsm** [comment]
Looks amazing @zenorocha, thank you so much. I'll close this issue,

Best regards,
oppsec.
