### ISSUE TITLE
Add support for IDA Pro version >= 7.3

### ISSUE THREAD

**Issue by mc-marcocheng** [dracula/ida#2]
IDA Pro version >= 7.3 does not support the theme import method with .clr file anymore. It requires .css file to change the theme. Can you make the theme available for these versions? Thanks.

Reference: https://github.com/0xItx/ida_nightfall

**Comment by 0xdsm** [comment]
Hey @mc-marcocheng 

Sorry to make you wait so long. 
I already released the support for IDA >= 7.3 and works for IDA Freeware too.

Best regards,
oppsec.
