### ISSUE TITLE
fix: website changes

### ISSUE THREAD

**Issue by 0xdsm** [dracula/ida#4]
Hello @zenorocha 

I want to know if you could change "IDA Pro" to just "IDA", the theme works for IDA Freeware too

![image](https://user-images.githubusercontent.com/50470310/134366845-bdc8cb7a-ff25-4702-ad9c-8c8f14c9e1a0.png)

Best regards,
oppsec

**Comment by ritwikrajput** [comment]
Well, I would like to give it a shot..!!
