### ISSUE TITLE
Register and Flags Labels

### ISSUE THREAD

**Issue by ghost** [dracula/ida#8]
When Debugging the Labels for the Registers and Flags are dark blue (This is the IDA Pro default I think). This makes them hard to read (at least on my system).
After some searching I've found that adding the following to the theme makes them a lot easier to read:

TCpuRegs ui_label_t
{
    color: #8398d4;
}

This Gives them the dark purple color that's also used in the decompiler (the lightest of the two), I don't know if this is the best color to use for this theme, but at least I can clearly read the labels now.
I hope this helps you improve this theme for everybody.

**Comment by 0xdsm** [comment]
Hi @patrick-kox 

Sorry for making you wait so long! 
I've implemented the CSS code that you've suggested, thanks for helping the theme! =)

Best regards,
oppsec.
